IF OBJECT_ID('THQMSMASTERSET','U') IS NOT NULL
DROP TABLE THQMSMASTERSET
GO

CREATE TABLE THQMSMASTERSET
(
	FID              BIGINT     IDENTITY(1,1),
	FREPORTDATESTR	 VARCHAR(255),
	FCODE            VARCHAR(50),
	FNAME            VARCHAR(255),
	FCONTENT         VARCHAR(50),
	FEXTEND          BIT,
	FPX              SMALLINT
)

GO
